In [4]:
import numpy as np

n, m = map(int, input().split())

a = np.array([[int(i) for i in input().split()] for _ in range(n)])
b = np.array([[int(i) for i in input().split()] for _ in range(n)])

print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.floor_divide(a, b))
print(np.mod(a, b))
print(np.power(a, b))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]
