In [5]:
import numpy as np
np.set_printoptions(legacy = '1.13')

n = np.array(list(map(float, input().split())))

print(np.floor(n))
print(np.ceil(n))
print(np.rint(n))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]
