In [3]:
import numpy as np

a = list(map(int, input().split()))
b = list(map(int, input().split()))

print(np.array(np.inner(a, b)))
print(np.array(np.outer(a, b)))

0 1
2 3
3
[[0 0]
 [2 3]]


In [5]:
import numpy as np

a = np.array(list(map(int, input().split())))
b = np.array(list(map(int, input().split())))

print(np.inner(a, b))
print(np.outer(a, b))

0 1
2 3
3
[[0 0]
 [2 3]]


In [6]:
import numpy as np

a, b = (np.array(input().split(), int) for _ in range(2))

print(np.inner(a, b), np.outer(a, b), sep = '\n')

0 1
2 3
3
[[0 0]
 [2 3]]
