In [12]:
import numpy as np

n = (input().split())
arr = np.array(n, int)

print(np.reshape(arr, (3, 3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
import numpy

arr = numpy.array(input().split(), int)
print(numpy.reshape(arr, (3, 3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
