In [49]:
import numpy as np

l1 = []
n, m = map(int, input().split())

for i in range(n):
    l1.append(list(map(int, input().split())))

b = np.array(l1)
print(b.transpose())
print(b.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [47]:
import numpy as np

N, M = map(int, input().split())

arr = np.array([list(map(int, input().split())) for _ in range(N)])

print(np.transpose(arr))
print(arr.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]
